[package]
name = "sensor_data"
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasmlib = "0.2.2"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
panic = "abort"

